### PR TITLE
Update dependencies with vulnerable transitive dependencies

### PR DESCRIPTION
**Pull request by koenpunt**
For Bouncycastle the [**jdk18on** jars are compiled to work with anything from Java 1.8 up.](https://www.bouncycastle.org/latest_releases.html#:~:text=jdk18on%20jars%20are%20compiled%20to%20work%20with%20anything%20from%20Java%201.8%20up).

The pushy dependency was already up to date in the pom.xml file.

### CODE REVIEW

**Review by drallgood — DISMISSED** [review]
Looks good. Thanks

**Review by drallgood — APPROVED** [review]

**Comment by drallgood** [comment]
Merged. Thanks 😜

**Comment by OBreidenbach** [comment]
Hi,
when will be the next release with these changes?
Best regards.

**Comment by drallgood** [comment]
@OBreidenbach oh. I thought I had released that already.

I will push in some more dependency updates. Then release it

**Comment by drallgood** [comment]
@OBreidenbach Published 0.4.0

Have look. I hope I didn't brake anything with all those changes to gradle and Java 11 etc

**Pull request merged**
