### PR TITLE
Support automatic synchronization for "barcode" & "barcodes":

### PR DESCRIPTION
**Pull request by stepio**
https://github.com/stepio/jpasskit/issues/14

### CODE REVIEW

**Comment by stepio** [comment]
In my opinion this feature would be nice in the API:
Pros:
 - less manual work to achieve best support by devices;
 - better data consistency.
Cons:
 - no way to specify different QR codes for iOS 8 & iOS 9

**Comment by stepio** [comment]
Inspired by my personal needs and the related issue in your repository:
https://github.com/drallgood/jpasskit/issues/66

**Comment by stepio** [comment]
Hi @drallgood,

Any update on this request? What do you think about the proposed changes?

**Comment by drallgood** [comment]
@stepio Sorry. Completely forgot about this.

Looks good.

**Pull request merged**
