### PR TITLE
Updates for signing utils & fixes for builing in Mac OS X with JDK 1.7

### PR DESCRIPTION
**Pull request by stepio**
Hi again,

Checked the latest version and would like to share several improvements

### CODE REVIEW

**Comment by drallgood** [comment]
Hi @stepio 

Thanks for the contribution!
Is there a reason, why you've introduced a java8 specific profile? Especially the GPG signing isn't really specific to Java 8. And in any case, there shouldn't be any issues building this with JDK7 (even on OS X).

**Comment by stepio** [comment]
Actually there are two profiles in the code:
 1. java8 specific is for "-Xdoclint:none" argument - I was unable to build with it using JDK7, so decided that using profile would be nice - argument is available for JDK8, but does not break the build for JDK7.
Took from here: http://stackoverflow.com/questions/27728733/javadoc-error-invalid-flag-xdoclintnone-when-i-use-java-7-but-it-works-i
2. Mac OS X profile is to ease build on non-Linux environment. I use mac and does not have gpg utility "out of the box". So allowing to build without it seems reasonable.

Still I expect that both features will still work in your environment.

**Comment by drallgood** [comment]
Sure they will.. if I don't forget to activate them ;)

Thanks for the explanation. Gonna merge it in a minute, once I've prepared Jenkins for it

**Comment by stepio** [comment]
Should be activated automaticaly with java 8 and linux - at least worked for me. Better try without manual activation first - if does not work, that's an issue.

**Comment by drallgood** [comment]
I think it's better if they aren't activated automatically. 
The GPG part should only ever be activated when you deploy the artifact (mvn deploy) to maven central/Sonatype.

**Comment by stepio** [comment]
I meant that I tried to keep the default configuration the same ;) Now you may tune the profiles for your needs if necessary.

**Pull request merged**
